# Generated by Django 4.0.6 on 2022-07-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
