# Generated by Django 4.0.5 on 2022-07-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newsletter', '0003_mailmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailMessage',
        ),
    ]
